### ISSUE TITLE
定义的interface和底下使用的interface不统一

### ISSUE THREAD

**Issue by boxjohn** [orca-team/vscode-tswagger#2]
![uTools_1693468034997](https://github.com/orca-team/vscode-tswagger/assets/40717144/15ea457b-1753-4117-96e6-64352e371e5f)
定义的interface和底下使用的interface不统一，而且模板不能自己编写，要传其他参数的时候很僵硬

**Comment by Orchardxyz** [comment]
您好，能给一份最小可复现该问题的 swagger json 吗？

**Comment by boxjohn** [comment]
> 您好，能给一份最小可复现该问题的 swagger json 吗？

[swagger.txt](https://github.com/orca-team/vscode-tswagger/files/12511230/swagger.txt)
生成的所有都这样

**Comment by Orchardxyz** [comment]
> > 您好，能给一份最小可复现该问题的 swagger json 吗？
> 
> [swagger.txt](https://github.com/orca-team/vscode-tswagger/files/12511230/swagger.txt) 生成的所有都这样

您好，本插件所使用的 [json-schema-to-typescrip](https://www.npmjs.com/package/json-schema-to-typescript) 会将小写开头的类型名称转化为大写开头，以符合 Typescript 的命名规范，因此会出现与接口方法中所使用的类型名称不一致的情况。

目前已增加了校验约束：

<img width="643" alt="issue02-reply" src="https://github.com/orca-team/vscode-tswagger/assets/43738751/eb43e2f9-0578-4d35-815f-873da3f16b9a">

对于已经生成的接口，您可以对接口再进行一次重命名。

感谢您在使用过程中的反馈🤝
